<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>FModel.ico</ApplicationIcon>
    <Version>4.4.4.0</Version>
    <IsPackable>false</IsPackable>
    <IsPublishable>true</IsPublishable>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <NeutralLanguage>en</NeutralLanguage>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <NoWarn>NU1701</NoWarn>
    <StartupObject>FModel.App</StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.xshd" />
    <EmbeddedResource Include="Resources\*.frag" />
    <EmbeddedResource Include="Resources\*.vert" />
    <EmbeddedResource Include="Resources\fa-brands-400.otf" />
    <EmbeddedResource Include="Resources\fa-solid-900.otf" />
    <EmbeddedResource Include="Resources\fa-regular-400.otf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="CSCore" Version="1.2.1.2" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="EpicManifestParser" Version="3.0.0-preview.1" />
    <PackageReference Include="FModel.AdonisUI" Version="1.18.0" />
    <PackageReference Include="FModel.AdonisUI.ClassicTheme" Version="1.18.0" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.8" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="[2.88.9]" />
    <PackageReference Include="Svg.Skia" Version="[4.8.0]" /> <!--because of skia 3.0 in newer versions-->
    <PackageReference Include="Twizzle.ImGui-Bundle.NET" Version="1.91.5.2" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CUE4Parse\CUE4Parse-Conversion\CUE4Parse-Conversion.csproj" />
    <ProjectReference Include="..\CUE4Parse\CUE4Parse\CUE4Parse.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\*.png" />
    <Resource Include="Resources\FModel.ico" />
    <Resource Include="Resources\BurbankBigCondensed-Bold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
