// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Parser;
//
//    var accessCode = AccessCode.FromJson(jsonString);

namespace FModel.Parser.Access.Code
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AccessCode
    {
        [JsonProperty("expiresInSeconds", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExpiresInSeconds { get; set; }

        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }

        [JsonProperty("creatingClientId", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatingClientId { get; set; }
    }

    public partial class AccessCode
    {
        public static AccessCode FromJson(string json) => JsonConvert.DeserializeObject<AccessCode>(json, FModel.Parser.Access.Code.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AccessCode self) => JsonConvert.SerializeObject(self, FModel.Parser.Access.Code.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
