//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About FModel.
        /// </summary>
        public static string AboutF {
            get {
                return ResourceManager.GetString("AboutF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FModel is a .PAK file explorer fully dedicated to Fortnite but also work with some other Unreal Engine&apos;s games.
        ///
        ///Created in March 2019, in order to have unique and personalized functionality, it quickly became popular through leakers who used it to quickly generate images of new cosmetics added to the game.
        ///Over time, new features got added and new users discovered the program.
        ///It&apos;s now the most used free software to leak on Fortnite..
        /// </summary>
        public static string AboutFDetails {
            get {
                return ResourceManager.GetString("AboutFDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to download {0} which has a size of {1}.
        /// </summary>
        public static string AboutToDownload {
            get {
                return ResourceManager.GetString("AboutToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory.
        /// </summary>
        public static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES.
        /// </summary>
        public static string AES {
            get {
                return ResourceManager.GetString("AES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Key.
        /// </summary>
        public static string AesKey {
            get {
                return ResourceManager.GetString("AesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys have been updated.
        /// </summary>
        public static string AesKeysUpdated {
            get {
                return ResourceManager.GetString("AesKeysUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not working with &apos;{1}&apos;.
        /// </summary>
        public static string AesNotWorking {
            get {
                return ResourceManager.GetString("AesNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents.
        /// </summary>
        public static string AllDocuments {
            get {
                return ResourceManager.GetString("AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing {0}.
        /// </summary>
        public static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon api {
            get {
                object obj = ResourceManager.GetObject("api", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon api_off {
            get {
                object obj = ResourceManager.GetObject("api_off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Devices.
        /// </summary>
        public static string AudioDevices {
            get {
                return ResourceManager.GetString("AudioDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Player.
        /// </summary>
        public static string AudioPlayer {
            get {
                return ResourceManager.GetString("AudioPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian English.
        /// </summary>
        public static string AustralianEnglish {
            get {
                return ResourceManager.GetString("AustralianEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto open sounds.
        /// </summary>
        public static string AutoOpenSounds {
            get {
                return ResourceManager.GetString("AutoOpenSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backup_restore {
            get {
                object obj = ResourceManager.GetObject("backup_restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup PAKs.
        /// </summary>
        public static string BackupPaks {
            get {
                return ResourceManager.GetString("BackupPaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        public static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon borderlands3 {
            get {
                object obj = ResourceManager.GetObject("borderlands3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British English.
        /// </summary>
        public static string BritishEnglish {
            get {
                return ResourceManager.GetString("BritishEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs Report.
        /// </summary>
        public static string BugsReport {
            get {
                return ResourceManager.GetString("BugsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BurbankBigCondensed_Bold {
            get {
                object obj = ResourceManager.GetObject("BurbankBigCondensed_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Per Second.
        /// </summary>
        public static string BytesPerSecond {
            get {
                return ResourceManager.GetString("BytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges&apos; Custom Banner.
        /// </summary>
        public static string ChallengesCustomBanner {
            get {
                return ResourceManager.GetString("ChallengesCustomBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges&apos; Theme Creator.
        /// </summary>
        public static string ChallengesThemeCreator {
            get {
                return ResourceManager.GetString("ChallengesThemeCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Game.
        /// </summary>
        public static string ChangeGame {
            get {
                return ResourceManager.GetString("ChangeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon check_circle {
            get {
                object obj = ResourceManager.GetObject("check_circle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified).
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ColorPickerOne {
            get {
                object obj = ResourceManager.GetObject("ColorPickerOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ColorPickerTwo {
            get {
                object obj = ResourceManager.GetObject("ColorPickerTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string Compression {
            get {
                return ResourceManager.GetString("Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap content_copy {
            get {
                object obj = ResourceManager.GetObject("content_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string ContributorsF {
            get {
                return ResourceManager.GetString("ContributorsF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Waddlesworth			• Maiky
        ///• FunGames			• Officer
        ///• PsychoPast			• TSG
        ///• GMatrixGames			• Jackson
        ///• XTigerHyperX			• FireMonkey
        ///• Mang0e.
        /// </summary>
        public static string ContributorsFDetails {
            get {
                return ResourceManager.GetString("ContributorsFDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image.
        /// </summary>
        public static string CopyImage {
            get {
                return ResourceManager.GetString("CopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create directory.
        /// </summary>
        public static string CouldNotCreateDirectory {
            get {
                return ResourceManager.GetString("CouldNotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cpp {
            get {
                object obj = ResourceManager.GetObject("Cpp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating {0}.
        /// </summary>
        public static string CreateError {
            get {
                return ResourceManager.GetString("CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully created.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        public static string CurrentDocument {
            get {
                return ResourceManager.GetString("CurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found, challenges&apos; custom theme disabled.
        /// </summary>
        public static string CustomBannerNotFound {
            get {
                return ResourceManager.GetString("CustomBannerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully exported.
        /// </summary>
        public static string DataExported {
            get {
                return ResourceManager.GetString("DataExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully saved.
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete_forever {
            get {
                object obj = ResourceManager.GetObject("delete_forever", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Name.
        /// </summary>
        public static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Path.
        /// </summary>
        public static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Server.
        /// </summary>
        public static string DiscordServer {
            get {
                return ResourceManager.GetString("DiscordServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donators.
        /// </summary>
        public static string DonatorsF {
            get {
                return ResourceManager.GetString("DonatorsF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Maiky ♥			• HYPEX ♥
        ///• VenomLeaks ♥			• JayKeyFN ♥
        ///• Fevers ♥			• Netu ♥
        ///• TheGameVlog ♥			• Quentin
        ///• Yanteh				• Shiina
        ///• SexyNutella			• Alexander
        ///• Jinx				• imatrix
        ///• Frenzy Leaks			• LlamaLeaks
        ///• XTigerHyperX			• FunGames
        ///• WeLoveFortnite.
        /// </summary>
        public static string DonatorsFDetails {
            get {
                return ResourceManager.GetString("DonatorsFDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading {0}.
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully downloaded.
        /// </summary>
        public static string DownloadSuccess {
            get {
                return ResourceManager.GetString("DownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics.
        /// </summary>
        public static string DrawStats {
            get {
                return ResourceManager.GetString("DrawStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not working with {1}.
        /// </summary>
        public static string DynamicKeyNotWorking {
            get {
                return ResourceManager.GetString("DynamicKeyNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Keys.
        /// </summary>
        public static string DynamicKeys {
            get {
                return ResourceManager.GetString("DynamicKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Directory.
        /// </summary>
        public static string EditDirectory {
            get {
                return ResourceManager.GetString("EditDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon egl2 {
            get {
                object obj = ResourceManager.GetObject("egl2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EIconDesign_Default {
            get {
                object obj = ResourceManager.GetObject("EIconDesign_Default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EIconDesign_Flat {
            get {
                object obj = ResourceManager.GetObject("EIconDesign_Flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EIconDesign_Mini {
            get {
                object obj = ResourceManager.GetObject("EIconDesign_Mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EIconDesign_NoBackground {
            get {
                object obj = ResourceManager.GetObject("EIconDesign_NoBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EIconDesign_NoText {
            get {
                object obj = ResourceManager.GetObject("EIconDesign_NoText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string Encrypted {
            get {
                return ResourceManager.GetString("Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction.
        /// </summary>
        public static string Extraction {
            get {
                return ResourceManager.GetString("Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBKP Files (*.fbkp)|*.fbkp|All Files (*.*)|*.*.
        /// </summary>
        public static string FbkpFilter {
            get {
                return ResourceManager.GetString("FbkpFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string FCopy {
            get {
                return ResourceManager.GetString("FCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FFile {
            get {
                return ResourceManager.GetString("FFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon file_image {
            get {
                object obj = ResourceManager.GetObject("file_image", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_multiple {
            get {
                object obj = ResourceManager.GetObject("file_multiple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count.
        /// </summary>
        public static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name w/o Extension.
        /// </summary>
        public static string FileNameNoExt {
            get {
                return ResourceManager.GetString("FileNameNoExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path w/o Extension.
        /// </summary>
        public static string FilePathNoExt {
            get {
                return ResourceManager.GetString("FilePathNoExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find And Replace.
        /// </summary>
        public static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string Flat {
            get {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FModel Launcher.
        /// </summary>
        public static string FLauncher {
            get {
                return ResourceManager.GetString("FLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fmodel {
            get {
                object obj = ResourceManager.GetObject("fmodel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_download {
            get {
                object obj = ResourceManager.GetObject("folder_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon fortnite {
            get {
                object obj = ResourceManager.GetObject("fortnite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Breakers.
        /// </summary>
        public static string GameName_BattleBreakers {
            get {
                return ResourceManager.GetString("GameName_BattleBreakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderlands 3.
        /// </summary>
        public static string GameName_Borderlands3 {
            get {
                return ResourceManager.GetString("GameName_Borderlands3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead By Daylight.
        /// </summary>
        public static string GameName_DeadByDaylight {
            get {
                return ResourceManager.GetString("GameName_DeadByDaylight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortnite.
        /// </summary>
        public static string GameName_Fortnite {
            get {
                return ResourceManager.GetString("GameName_Fortnite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Dungeons.
        /// </summary>
        public static string GameName_MinecraftDungeons {
            get {
                return ResourceManager.GetString("GameName_MinecraftDungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue Company.
        /// </summary>
        public static string GameName_RogueCompany {
            get {
                return ResourceManager.GetString("GameName_RogueCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellbreak.
        /// </summary>
        public static string GameName_Spellbreak {
            get {
                return ResourceManager.GetString("GameName_Spellbreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of Decay 2.
        /// </summary>
        public static string GameName_StateofDecay2 {
            get {
                return ResourceManager.GetString("GameName_StateofDecay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cycle.
        /// </summary>
        public static string GameName_TheCycle {
            get {
                return ResourceManager.GetString("GameName_TheCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Outer Worlds.
        /// </summary>
        public static string GameName_TheOuterWorlds {
            get {
                return ResourceManager.GetString("GameName_TheOuterWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valorant.
        /// </summary>
        public static string GameName_Valorant {
            get {
                return ResourceManager.GetString("GameName_Valorant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue, Saturation, Value.
        /// </summary>
        public static string Hsv {
            get {
                return ResourceManager.GetString("Hsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Creator.
        /// </summary>
        public static string IconCreator {
            get {
                return ResourceManager.GetString("IconCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Watermark.
        /// </summary>
        public static string IconWatermark {
            get {
                return ResourceManager.GetString("IconWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found, watermarking disabled.
        /// </summary>
        public static string IconWatermarkNotFound {
            get {
                return ResourceManager.GetString("IconWatermarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Idling.
        /// </summary>
        public static string Idling {
            get {
                return ResourceManager.GetString("Idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image successfully saved.
        /// </summary>
        public static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Merger.
        /// </summary>
        public static string ImagesMerger {
            get {
                return ResourceManager.GetString("ImagesMerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Ini {
            get {
                object obj = ResourceManager.GetObject("Ini", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language set to {0}.
        /// </summary>
        public static string InternationalizationStatus {
            get {
                return ResourceManager.GetString("InternationalizationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Part Of.
        /// </summary>
        public static string IsPartOf {
            get {
                return ResourceManager.GetString("IsPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Json {
            get {
                object obj = ResourceManager.GetObject("Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files (*.json)|*.json.
        /// </summary>
        public static string JsonFilter {
            get {
                return ResourceManager.GetString("JsonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Type.
        /// </summary>
        public static string JsonType {
            get {
                return ResourceManager.GetString("JsonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening - {0}.
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All.
        /// </summary>
        public static string LoadAll {
            get {
                return ResourceManager.GetString("LoadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Mode.
        /// </summary>
        public static string LoadingMode {
            get {
                return ResourceManager.GetString("LoadingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Modified Files.
        /// </summary>
        public static string LoadModifiedFiles {
            get {
                return ResourceManager.GetString("LoadModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load New Files.
        /// </summary>
        public static string LoadNewFiles {
            get {
                return ResourceManager.GetString("LoadNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load New and Modified Files.
        /// </summary>
        public static string LoadNewModifiedFiles {
            get {
                return ResourceManager.GetString("LoadNewModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon lock_open_variant {
            get {
                object obj = ResourceManager.GetObject("lock_open_variant", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main PAKs:.
        /// </summary>
        public static string MainPaks {
            get {
                return ResourceManager.GetString("MainPaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        public static string MatchWholeWord {
            get {
                return ResourceManager.GetString("MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe Later.
        /// </summary>
        public static string MaybeLater {
            get {
                return ResourceManager.GetString("MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalist.
        /// </summary>
        public static string Minimalist {
            get {
                return ResourceManager.GetString("Minimalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Files.
        /// </summary>
        public static string ModifiedFiles {
            get {
                return ResourceManager.GetString("ModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mounted to {1}.
        /// </summary>
        public static string MountedPakTo {
            get {
                return ResourceManager.GetString("MountedPakTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Point.
        /// </summary>
        public static string MountPoint {
            get {
                return ResourceManager.GetString("MountPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Files.
        /// </summary>
        public static string NewFiles {
            get {
                return ResourceManager.GetString("NewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New and Modified Files.
        /// </summary>
        public static string NewModifiedFiles {
            get {
                return ResourceManager.GetString("NewModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Background.
        /// </summary>
        public static string NoBackground {
            get {
                return ResourceManager.GetString("NoBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no data to export.
        /// </summary>
        public static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no data to save.
        /// </summary>
        public static string NoDataToSave {
            get {
                return ResourceManager.GetString("NoDataToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no image to copy.
        /// </summary>
        public static string NoImageToCopy {
            get {
                return ResourceManager.GetString("NoImageToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no image to save.
        /// </summary>
        public static string NoImageToSave {
            get {
                return ResourceManager.GetString("NoImageToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your internet connection is currently not working.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An encrypted .PAK file has been found. In order to decrypt it, please specify a working AES encryption key.
        /// </summary>
        public static string NoKeyWarning {
            get {
                return ResourceManager.GetString("NoKeyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Text.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offsets.
        /// </summary>
        public static string Offsets {
            get {
                return ResourceManager.GetString("Offsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGG Files (*.ogg)|*.ogg|WAV Files (*.wav)|*.wav|WEM Files (*.wem)|*.wem|ADPCM Files (*.adpcm)|*.adpcm|All Files (*.*)|*.*.
        /// </summary>
        public static string OggFilter {
            get {
                return ResourceManager.GetString("OggFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        public static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Output Folder.
        /// </summary>
        public static string OpenOutputFolder {
            get {
                return ResourceManager.GetString("OpenOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sounds.
        /// </summary>
        public static string OpenSounds {
            get {
                return ResourceManager.GetString("OpenSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string Packages {
            get {
                return ResourceManager.GetString("Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAK.
        /// </summary>
        public static string PAK {
            get {
                return ResourceManager.GetString("PAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can now be opened.
        /// </summary>
        public static string PakCanBeOpened {
            get {
                return ResourceManager.GetString("PakCanBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is locked by another process.
        /// </summary>
        public static string PakFileLocked {
            get {
                return ResourceManager.GetString("PakFileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAK Files.
        /// </summary>
        public static string PakFiles {
            get {
                return ResourceManager.GetString("PakFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing of {0} types isn&apos;t supported yet..
        /// </summary>
        public static string ParsingNotSupported {
            get {
                return ResourceManager.GetString("ParsingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .PAK Files Auto Detected.
        /// </summary>
        public static string PathAutoDetected {
            get {
                return ResourceManager.GetString("PathAutoDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FModel Path(s) Changed.
        /// </summary>
        public static string PathChanged {
            get {
                return ResourceManager.GetString("PathChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FModel is about to restart because you applied your new path(s).
        /// </summary>
        public static string PathChangedRestart {
            get {
                return ResourceManager.GetString("PathChangedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap playlist_plus {
            get {
                object obj = ResourceManager.GetObject("playlist_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Files (*.png)|*.png|All Files (*.*)|*.*.
        /// </summary>
        public static string PngFilter {
            get {
                return ResourceManager.GetString("PngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        public static string PortugueseBrazil {
            get {
                return ResourceManager.GetString("PortugueseBrazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Portugal).
        /// </summary>
        public static string PortuguesePortugal {
            get {
                return ResourceManager.GetString("PortuguesePortugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap power {
            get {
                object obj = ResourceManager.GetObject("power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap progress_download {
            get {
                object obj = ResourceManager.GetObject("progress_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        public static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload AES keys at launch.
        /// </summary>
        public static string ReloadAesKeysAtLaunch {
            get {
                return ResourceManager.GetString("ReloadAesKeysAtLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Directory.
        /// </summary>
        public static string RemoveDirectory {
            get {
                return ResourceManager.GetString("RemoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed or renamed cosmetics:.
        /// </summary>
        public static string RemovedRenamedCosmetics {
            get {
                return ResourceManager.GetString("RemovedRenamedCosmetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace With:.
        /// </summary>
        public static string ReplaceWith {
            get {
                return ResourceManager.GetString("ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Layout.
        /// </summary>
        public static string RestoreLayout {
            get {
                return ResourceManager.GetString("RestoreLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red, Green, Blue, Alpha.
        /// </summary>
        public static string Rgba {
            get {
                return ResourceManager.GetString("Rgba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully saved.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search In:.
        /// </summary>
        public static string SearchIn {
            get {
                return ResourceManager.GetString("SearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Up.
        /// </summary>
        public static string SearchUp {
            get {
                return ResourceManager.GetString("SearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap share {
            get {
                object obj = ResourceManager.GetObject("share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap share_all {
            get {
                object obj = ResourceManager.GetObject("share_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sign_direction_plus {
            get {
                object obj = ResourceManager.GetObject("sign_direction_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sign_direction_remove {
            get {
                object obj = ResourceManager.GetObject("sign_direction_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this Version.
        /// </summary>
        public static string SkipThisVersion {
            get {
                return ResourceManager.GetString("SkipThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Latin America).
        /// </summary>
        public static string SpanishLatin {
            get {
                return ResourceManager.GetString("SpanishLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Mexico).
        /// </summary>
        public static string SpanishMexico {
            get {
                return ResourceManager.GetString("SpanishMexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string SRefresh {
            get {
                return ResourceManager.GetString("SRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Key.
        /// </summary>
        public static string StaticKey {
            get {
                return ResourceManager.GetString("StaticKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not working with your PAK files.
        /// </summary>
        public static string StaticKeyNotWorking {
            get {
                return ResourceManager.GetString("StaticKeyNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stop1 {
            get {
                object obj = ResourceManager.GetObject("stop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T_ClipSize_Weapon_Stats {
            get {
                object obj = ResourceManager.GetObject("T_ClipSize_Weapon_Stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T_DamagePerBullet_Weapon_Stats {
            get {
                object obj = ResourceManager.GetObject("T_DamagePerBullet_Weapon_Stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T_Icon_Pets_64 {
            get {
                object obj = ResourceManager.GetObject("T_Icon_Pets_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T_Icon_Quests_64 {
            get {
                object obj = ResourceManager.GetObject("T_Icon_Quests_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T_Placeholder_Challenge_Image {
            get {
                object obj = ResourceManager.GetObject("T_Placeholder_Challenge_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T_Placeholder_Item_Image {
            get {
                object obj = ResourceManager.GetObject("T_Placeholder_Item_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T_ReloadTime_Weapon_Stats {
            get {
                object obj = ResourceManager.GetObject("T_ReloadTime_Weapon_Stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string TB {
            get {
                return ResourceManager.GetString("TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Find:.
        /// </summary>
        public static string TextToFind {
            get {
                return ResourceManager.GetString("TextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Elapsed {0}ms.
        /// </summary>
        public static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} assets.
        /// </summary>
        public static string TotalAssetsLoaded {
            get {
                return ResourceManager.GetString("TotalAssetsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size.
        /// </summary>
        public static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Traditional).
        /// </summary>
        public static string TraditionalChinese {
            get {
                return ResourceManager.GetString("TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        public static string TranslatorsF {
            get {
                return ResourceManager.GetString("TranslatorsF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • EN: Asval#2291			• FR: Asval#2291
        ///• DE: FunGames#6822		• IT: arianaglande#5581
        ///• ES: Maiky.M#9879		• AR: PsychoPast#0001
        ///• JA: FNJPNews#7820		• RU: Seawod#4311
        ///• CN: GMatrixGames#6929.
        /// </summary>
        public static string TranslatorsFDetails {
            get {
                return ResourceManager.GetString("TranslatorsFDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trello.
        /// </summary>
        public static string Trello {
            get {
                return ResourceManager.GetString("Trello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred: {0}.
        /// </summary>
        public static string UnhandledExceptionOccured {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FModel {0} is available. You are using version {1}. Do you want to update the application now?.
        /// </summary>
        public static string UpdateAvailableConfirm {
            get {
                return ResourceManager.GetString("UpdateAvailableConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check Failed.
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem reaching the update server, please check your internet connection or try again later..
        /// </summary>
        public static string UpdateReachServerProblem {
            get {
                return ResourceManager.GetString("UpdateReachServerProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Discord RPC.
        /// </summary>
        public static string UseDiscordRpc {
            get {
                return ResourceManager.GetString("UseDiscordRpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use game colors.
        /// </summary>
        public static string UseGameColors {
            get {
                return ResourceManager.GetString("UseGameColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use item shop icon.
        /// </summary>
        public static string UseItemShopIcon {
            get {
                return ResourceManager.GetString("UseItemShopIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Watermark.
        /// </summary>
        public static string UseWatermark {
            get {
                return ResourceManager.GetString("UseWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon valorant_live {
            get {
                object obj = ResourceManager.GetObject("valorant_live", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese (Vietnam).
        /// </summary>
        public static string VietnameseVietnam {
            get {
                return ResourceManager.GetString("VietnameseVietnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap volume_minus {
            get {
                object obj = ResourceManager.GetObject("volume_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap volume_mute {
            get {
                object obj = ResourceManager.GetObject("volume_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap volume_plus {
            get {
                object obj = ResourceManager.GetObject("volume_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        public static string Watermark {
            get {
                return ResourceManager.GetString("Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon wifi_strength_off {
            get {
                object obj = ResourceManager.GetObject("wifi_strength_off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards.
        /// </summary>
        public static string Wildcards {
            get {
                return ResourceManager.GetString("Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position / Value.
        /// </summary>
        public static string WithPosition {
            get {
                return ResourceManager.GetString("WithPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Xml {
            get {
                object obj = ResourceManager.GetObject("Xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (Show the Changelog).
        /// </summary>
        public static string YesShowChangelog {
            get {
                return ResourceManager.GetString("YesShowChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zulu.
        /// </summary>
        public static string Zulu {
            get {
                return ResourceManager.GetString("Zulu", resourceCulture);
            }
        }
    }
}
