// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using FModel.Parser.LocResParser;
//
//    var locResParser = LocResParser.FromJson(jsonString);

namespace FModel.Parser.LocResParser
{
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LocResParser
    {
        [JsonProperty("LocResText")]
        public string LocResText { get; set; }

        [JsonProperty("WorkerSetBonusTraitPattern")]
        public string WorkerSetBonusTraitPattern { get; set; }
    }

    public partial class LocResParser
    {
        public static LocResParser FromJson(string json) => JsonConvert.DeserializeObject<LocResParser>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this LocResParser self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
